#include <iostream>
#include <exception>
using namespace std;

double division(int a, int b) {
    if (b == 0) {
        throw"Division by zero condition!";
    }
    else if(b == -1) {
        throw b;
    }
    return a / b;

}

int main() {
    int x, y;
    cin >> x >> y;
    double z = 0;

    try {
        z = division(x, y);
        cout << z << endl;
    }
    catch (const char* e) {
        cout << e << endl;
    }
    catch (...)
    {
        cout << "exception" << endl;
    }
    return 0;
}
