#include <exception>
#include <limits>
#include <iostream>

using namespace std;

void MyFunc(int c)
{
    if (c > numeric_limits< short> ::max())
        throw invalid_argument("MyFunc argument too large.");
    else
        throw c;
}

int main()
{
    try
    {
        int num;
        cin >> num;
        MyFunc(num);
    }

    catch (exception& e)
    {
        cerr << e.what() << endl;
    }
    catch (short f)
    {
        cout << f << endl;
    }
    return 0;
}
