#include <iostream>
#include <string>
using namespace std;


int main(){
    cout << "Start" << endl;
    try {
        cout << "Inside try block"<< endl;
        throw 99;
        cout << "This will not execute";
    }
    catch (int i)
    {
        cout << "Caught an exception -- value i s : ";
        cout << i << endl;
    }
    cout << "End" << endl;
    return 0;
}
